/*
 * -----------------------------------------------------------------------------
 *  Author: Dusan Cubik
 *  Project: Physically Based Renderer for WebGPU
 *  Institution: Masaryk University
 *  Date: 16. 12. 2024
 *  File: Buffer.hpp
 *
 *  Description:
 *  The Buffer class encapsulates a WebGPU buffer, providing functionality to create buffers and write data into them.
 *  The Buffer class was generated by ChatGPT.
 * 
 * -----------------------------------------------------------------------------
 */
#pragma once
#include "wgpu_context.h"

class Buffer {
	public:
		Buffer(WGPUDevice _device, WGPUBufferUsageFlags _flags, uint64_t _size);
		void write(WGPUQueue _queue, const void* data, uint64_t offset);
		void write(WGPUQueue _queue, const void* data, uint64_t offset, uint64_t _size);
		WGPUBuffer getBuffer() { return buffer; }
		uint64_t getSize() { return size; }
	private:
		WGPUBuffer buffer;
		uint64_t size;
};